### ISSUE TITLE
Regarding ModuleNotFoundError: No module named 'gluonts.distribution'

### ISSUE THREAD

**Issue by wenouyang** [awslabs/gluon-ts#1575]
When trying to import distribution as

`from gluonts.distribution.neg_binomial import NegativeBinomialOutput

 `
The following error message is generated

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-21482f50f8f5> in <module>
----> 1 from gluonts.distribution.neg_binomial import NegativeBinomialOutput

ModuleNotFoundError: No module named 'gluonts.distribution'

from gluonts.distribution.neg_binomial import NegativeBinomialOutput
from gluonts.model.deepar import DeepAREstimator
```

**Comment by lostella** [comment]
@wenouyang where did you find such an import path? You should be doing 

```
from gluonts.mx.distribution.neg_binomial import NegativeBinomialOutput
```

**Comment by wenouyang** [comment]
@lostella , thanks for the response, I was trying to test the code listed here
https://www.kaggle.com/steverab/m5-forecasting-competition-gluonts-template

Is that due to the version update of Gluonts? Thanks.

**Comment by wenouyang** [comment]
The issue is solved.

**Comment by lostella** [comment]
> Is that due to the version update of Gluonts? Thanks.

Yes, exactly, there has been some reorganization of the package structure, sorry for the inconvenience :-)

This came with the 0.7.0 release, [see the notes](https://github.com/awslabs/gluon-ts/releases/tag/v0.7.0)
You can also check #1183 to see exactly what moved where

**Comment by AbhayGoyal** [comment]
hi, I am still getting this issue, what is the correct path for it?

**Comment by Dittonal** [comment]
> 

maybe try python3.7
