### ISSUE TITLE
pandas-offsets stopped being hashable

### ISSUE THREAD

**Issue by jaheba** [awslabs/gluon-ts#958]
In Pandas 1.1 the `freq` component of the time-stamps that we use have stopped being hashable, which means, they cannot be used as keys in dictionaries. We use this in different locations in our code base.

We now have two options:

* open an issue with pandas, requesting that the old behaviour is restored
* change our code to not make use of this feauture

**Comment by AaronSpieler** [comment]
For now we should probably change the pandas requirement to `<1.1`. 
I also ran into problems with the pandas version.

**Comment by PhilipMachineLearning** [comment]
Still an issue.

**Comment by lostella** [comment]
@PhilipMachineLearning do you have an example to reproduce the issue?

**Comment by Forecastlife** [comment]
Still an issue 4/23/2021

**Comment by jaheba** [comment]
> Still an issue 4/23/2021

This should be fixed now in pandas. What version are you using?

**Comment by tonyhoo** [comment]
Just for whoever still have the issue. 2 quick fixes:
1. Downgrade pandas to 1.0.x
2. Upgrade pandas to >1.3.x
